name: Trim CSV Pipeline
on:
  push:
    branches:
      - main
jobs:
  trim:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      # - name: Get changed files
      #   id: changed-files
      #   run: |
      #     git fetch --prune
      #     echo "changed_files=$(git diff-tree --no-commit-id --name-only -r ${{ github.sha }})" >> %GITHUB_OUTPUT
      # - name: Trim CSV files
      #   run: |
      #     for file in ${changed_files}; do
      #       echo "Trimming $file"
      #       ./trim_csv.sh "input/${file}" > "output/${file::-4}"
      #     done
      - name: Trim CSV files
        run: |
          for file in $(ls input); do
            echo "Trimming $file"
            ./trim_csv.sh "input/${file}" > "output/${file::-4}"
          done
      - name: Commit changes
        run: |
          git config --global user.name "GH Pipeline"
          git config --global user.email "info@krobier.com"
          git add output/*
          git commit -m "Added trimmed CSV files"
          git push